// Auto-generated by the Dockerfile during CI/CD builds.
// The build arg FIRMWARE_VERSION (git short SHA) overrides this via:
//   --build-property "compiler.cpp.extra_flags=-DFIRMWARE_VERSION=\"<sha>\""
// For local development builds the fallback below is used instead.
#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "dev"
#endif
